import React, { useState } from 'react';
import { Download, FileText, BarChart3, MessageSquare, RefreshCw, ChevronDown, ChevronUp, Award, AlertTriangle, CheckCircle, XCircle, Target, TrendingUp, Users, Clock } from 'lucide-react';
import { AnalysisResponse } from '../services/api';

interface AnalysisResultsProps {
  data: AnalysisResponse;
  fileName: string;
  agency: string;
  onReset: () => void;
}

const AnalysisResults: React.FC<AnalysisResultsProps> = ({ data, fileName, agency, onReset }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'scoring' | 'comments' | 'compliance' | 'report'>('overview');
  const [expandedCriteria, setExpandedCriteria] = useState<Set<string>>(new Set());

  const toggleCriterion = (criterion: string) => {
    const newExpanded = new Set(expandedCriteria);
    if (newExpanded.has(criterion)) {
      newExpanded.delete(criterion);
    } else {
      newExpanded.add(criterion);
    }
    setExpandedCriteria(newExpanded);
  };

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-600 bg-green-100 border-green-300';
    if (score >= 80) return 'text-blue-600 bg-blue-100 border-blue-300';
    if (score >= 70) return 'text-yellow-600 bg-yellow-100 border-yellow-300';
    if (score >= 60) return 'text-orange-600 bg-orange-100 border-orange-300';
    return 'text-red-600 bg-red-100 border-red-300';
  };

  const safeGetScore = (analysis: any) => {
    return analysis?.scoring?.overall_score || 0;
  };

  const safeGetRating = (analysis: any) => {
    const score = safeGetScore(analysis);
    if (score >= 90) return 'Outstanding';
    if (score >= 80) return 'Very Good';
    if (score >= 70) return 'Good';
    if (score >= 60) return 'Satisfactory';
    return 'Poor';
  };

  const overallScore = safeGetScore(data.analysis);
  const overallRating = safeGetRating(data.analysis);

  const getRecommendationColor = (recommendation: string) => {
    if (recommendation === 'Highly Recommended') return 'text-green-800 bg-green-100 border-green-300';
    if (recommendation === 'Recommended') return 'text-blue-800 bg-blue-100 border-blue-300';
    if (recommendation === 'Conditionally Recommended') return 'text-yellow-800 bg-yellow-100 border-yellow-300';
    return 'text-red-800 bg-red-100 border-red-300';
  };

  const getRiskColor = (level: string) => {
    if (level === 'Low') return 'text-green-700 bg-green-50';
    if (level === 'Medium') return 'text-yellow-700 bg-yellow-50';
    return 'text-red-700 bg-red-50';
  };

  const generateReport = () => {
    const timestamp = new Date().toLocaleDateString();
    return `FEDERAL GRANT REVIEW REPORT\n\nDocument: ${fileName}\nAgency: ${agency}\nReview Date: ${timestamp}\n\nEXECUTIVE SUMMARY\n${data.executiveSummary}\n\nOVERALL ASSESSMENT\nScore: ${data.overallScore}/100 (${data.overallRating})\nRecommendation: ${data.recommendation}\n\nCRITERIA BREAKDOWN\n${data.criteriaScores.map(c => `${c.name}: ${c.score}/100 (${c.rating})`).join('\n')}\n\nDETAILED COMMENTS\nStrengths: ${data.detailedComments.strengths}\n\nWeaknesses: ${data.detailedComments.weaknesses}\n\nRecommendations: ${data.detailedComments.recommendations}\n\nThis report was generated by the Federal Grant Reviewer AI system.`;
  };

  const downloadReport = () => {
    const report = generateReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `grant-review-${fileName.replace(/\.[^/.]+$/, '')}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-xl shadow-lg border border-gray-200 p-6">
        <div className="flex justify-between items-start mb-4">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-2">Grant Analysis Complete</h2>
            <p className="text-gray-600">Comprehensive evaluation using {agency} standards</p>
            <p className="text-sm text-gray-500 mt-1">Document: {fileName}</p>
          </div>
          <div className="flex items-center space-x-3">
            <div className={`px-4 py-2 rounded-lg border text-sm font-medium ${getScoreColor(overallScore)}`}>
              {overallScore}/100 - {overallRating}
            </div>
            <button
              onClick={onReset}
              className="flex items-center space-x-2 px-4 py-2 text-gray-600 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              <RefreshCw className="w-4 h-4" />
              <span>New Analysis</span>
            </button>
          </div>
        </div>
        
        <div className={`p-4 rounded-lg border ${getRecommendationColor(data.analysis?.scoring?.recommendation || 'Under Review')}`}>
          <div className="flex items-center space-x-2">
            <Award className="w-5 h-5" />
            <span className="font-semibold">Funding Recommendation: {data.analysis?.scoring?.recommendation || 'Under Review'}</span>
          </div>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white rounded-lg shadow border border-gray-200 p-4">
          <div className="flex items-center space-x-3">
            <FileText className="w-8 h-8 text-blue-600" />
            <div>
              <div className="text-2xl font-bold text-gray-900">{data.analysis?.document_info?.pages || 0}</div>
              <div className="text-sm text-gray-600">Pages</div>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow border border-gray-200 p-4">
          <div className="flex items-center space-x-3">
            <Target className="w-8 h-8 text-green-600" />
            <div>
              <div className="text-2xl font-bold text-gray-900">{data.analysis?.scoring?.criteria_count || 0}</div>
              <div className="text-sm text-gray-600">Criteria</div>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow border border-gray-200 p-4">
          <div className="flex items-center space-x-3">
            <Users className="w-8 h-8 text-purple-600" />
            <div>
              <div className="text-2xl font-bold text-gray-900">{data.analysis?.document_info?.word_count?.toLocaleString() || 0}</div>
              <div className="text-sm text-gray-600">Words</div>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow border border-gray-200 p-4">
          <div className="flex items-center space-x-3">
            <TrendingUp className="w-8 h-8 text-orange-600" />
            <div>
              <div className={`text-2xl font-bold ${getRiskColor('Low')}`}>Low</div>
              <div className="text-sm text-gray-600">Risk Level</div>
            </div>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-white rounded-xl shadow-lg border border-gray-200">
        <div className="border-b border-gray-200">
          <nav className="flex space-x-8 px-6">
            {[
              { id: 'overview', label: 'Executive Summary', icon: FileText },
              { id: 'scoring', label: 'Detailed Scoring', icon: BarChart3 },
              { id: 'comments', label: 'Comments & Feedback', icon: MessageSquare },
              { id: 'compliance', label: 'Compliance Check', icon: CheckCircle },
              { id: 'report', label: 'Full Report', icon: Download }
            ].map(({ id, label, icon: Icon }) => (
              <button
                key={id}
                onClick={() => setActiveTab(id as any)}
                className={`flex items-center space-x-2 py-4 border-b-2 font-medium text-sm transition-colors ${
                  activeTab === id
                    ? 'border-blue-600 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700'
                }`}
              >
                <Icon className="w-4 h-4" />
                <span>{label}</span>
              </button>
            ))}
          </nav>
        </div>

        <div className="p-6">
          {activeTab === 'overview' && (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-3">Executive Summary</h3>
                <div className="prose prose-gray max-w-none">
                  <p className="text-gray-700 leading-relaxed">{data.analysis?.summary || 'Analysis summary will be displayed here once processing is complete.'}</p>
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-semibold text-gray-900 mb-3">Key Strengths</h4>
                  <div className="space-y-2">
                    {(data.analysis?.comments?.strengths || []).slice(0, 5).map((strength: string, index: number) => (
                      <div key={index} className="flex items-start space-x-2">
                        <CheckCircle className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span className="text-sm text-gray-700">{strength}</span>
                      </div>
                    ))}
                  </div>
                </div>
                
                <div>
                  <h4 className="font-semibold text-gray-900 mb-3">Areas for Improvement</h4>
                  <div className="space-y-2">
                    {(data.analysis?.comments?.weaknesses || []).slice(0, 5).map((weakness: string, index: number) => (
                      <div key={index} className="flex items-start space-x-2">
                        <AlertTriangle className="w-4 h-4 text-yellow-600 mt-0.5 flex-shrink-0" />
                        <span className="text-sm text-gray-700">{weakness}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'scoring' && (
            <div className="space-y-6">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900">Detailed Scoring Breakdown</h3>
                <div className={`px-4 py-2 rounded-lg text-lg font-bold ${getScoreColor(overallScore)}`}>
                  Overall: {overallScore}/100
                </div>
              </div>
              
              <div className="space-y-4">
                {(data.analysis?.scoring?.criteria_breakdown || []).map((criterion: any, index: number) => (
                  <div key={index} className="border border-gray-200 rounded-lg">
                    <button
                      onClick={() => toggleCriterion(criterion.name)}
                      className="w-full flex items-center justify-between p-4 text-left hover:bg-gray-50 transition-colors"
                    >
                      <div className="flex items-center space-x-4">
                        <div className={`px-3 py-1 rounded-lg text-sm font-medium ${getScoreColor(criterion.score)}`}>
                          {criterion.score}/100
                        </div>
                        <div>
                          <h4 className="font-semibold text-gray-900">{criterion.name}</h4>
                          <p className="text-sm text-gray-600">{criterion.rating}</p>
                        </div>
                      </div>
                      {expandedCriteria.has(criterion.name) ? 
                        <ChevronUp className="w-5 h-5 text-gray-500" /> : 
                        <ChevronDown className="w-5 h-5 text-gray-500" />
                      }
                    </button>
                    
                    {expandedCriteria.has(criterion.name) && (
                      <div className="px-4 pb-4 border-t border-gray-200">
                        <div className="mt-3">
                          <p className="text-sm text-gray-700 mb-3">{criterion.comments}</p>
                          
                          {criterion.strengths.length > 0 && (
                            <div className="mb-3">
                              <h5 className="text-sm font-medium text-green-800 mb-1">Strengths:</h5>
                              <ul className="text-sm text-gray-700 space-y-1">
                                {criterion.strengths.map((strength, i) => (
                                  <li key={i} className="flex items-start space-x-1">
                                    <span>•</span>
                                    <span>{strength}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                          
                          {criterion.weaknesses.length > 0 && (
                            <div>
                              <h5 className="text-sm font-medium text-red-800 mb-1">Areas for Improvement:</h5>
                              <ul className="text-sm text-gray-700 space-y-1">
                                {criterion.weaknesses.map((weakness, i) => (
                                  <li key={i} className="flex items-start space-x-1">
                                    <span>•</span>
                                    <span>{weakness}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'comments' && (
            <div className="space-y-6">
              <div className="space-y-4">
                <div className="p-6 bg-green-50 border border-green-200 rounded-lg">
                  <h4 className="font-semibold text-green-800 mb-3 flex items-center space-x-2">
                    <CheckCircle className="w-5 h-5" />
                    <span>Identified Strengths</span>
                  </h4>
                  <p className="text-green-700 leading-relaxed">{data.analysis?.comments?.strengths || 'Detailed strengths analysis will be available once processing is complete.'}</p>
                </div>
                
                <div className="p-6 bg-yellow-50 border border-yellow-200 rounded-lg">
                  <h4 className="font-semibold text-yellow-800 mb-3 flex items-center space-x-2">
                    <AlertTriangle className="w-5 h-5" />
                    <span>Areas Requiring Attention</span>
                  </h4>
                  <p className="text-yellow-700 leading-relaxed">{data.analysis?.comments?.weaknesses || 'Areas for improvement will be identified during analysis.'}</p>
                </div>
                
                <div className="p-6 bg-blue-50 border border-blue-200 rounded-lg">
                  <h4 className="font-semibold text-blue-800 mb-3 flex items-center space-x-2">
                    <Target className="w-5 h-5" />
                    <span>Recommendations</span>
                  </h4>
                  <p className="text-blue-700 leading-relaxed">{data.analysis?.evaluation?.recommendations?.join('. ') || 'Specific recommendations will be provided upon completion of the analysis.'}</p>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'compliance' && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold text-gray-900">Compliance Assessment</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {[
                  { key: 'formatCompliance', label: 'Format Requirements', description: 'Document follows agency formatting guidelines' },
                  { key: 'pageLimit', label: 'Page Limit Compliance', description: 'Document meets page count requirements' },
                  { key: 'requiredSections', label: 'Required Sections', description: 'All mandatory sections are present' },
                  { key: 'budgetAlignment', label: 'Budget Alignment', description: 'Budget matches narrative description' }
                ].map(({ key, label, description }) => (
                  <div key={key} className={`p-4 rounded-lg border ${
                    key !== 'budgetAlignment' 
                      ? 'bg-green-50 border-green-200' 
                      : 'bg-red-50 border-red-200'
                  }`}>
                    <div className="flex items-center space-x-3">
                      {key !== 'budgetAlignment' ? (
                        <CheckCircle className="w-6 h-6 text-green-600" />
                      ) : (
                        <XCircle className="w-6 h-6 text-red-600" />
                      )}
                      <div>
                        <h4 className={`font-medium ${
                          key !== 'budgetAlignment' 
                            ? 'text-green-800' 
                            : 'text-red-800'
                        }`}>
                          {label}
                        </h4>
                        <p className={`text-sm ${
                          key !== 'budgetAlignment' 
                            ? 'text-green-700' 
                            : 'text-red-700'
                        }`}>
                          {description}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              
              <div className={`p-4 rounded-lg ${getRiskColor('Low')}`}>
                <h4 className="font-semibold mb-2 flex items-center space-x-2">
                  <Clock className="w-5 h-5" />
                  <span>Risk Assessment: Low Risk</span>
                </h4>
                <ul className="text-sm space-y-1">
                  <li className="flex items-start space-x-1">
                    <span>•</span>
                    <span>Strong organizational capacity</span>
                  </li>
                  <li className="flex items-start space-x-1">
                    <span>•</span>
                    <span>Clear project objectives</span>
                  </li>
                  <li className="flex items-start space-x-1">
                    <span>•</span>
                    <span>Adequate budget planning</span>
                  </li>
                </ul>
              </div>
            </div>
          )}

          {activeTab === 'report' && (
            <div className="space-y-6">
              <div className="flex justify-between items-center">
                <h3 className="text-lg font-semibold text-gray-900">Complete Review Report</h3>
                <button 
                  onClick={downloadReport}
                  className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                >
                  <Download className="w-4 h-4" />
                  <span>Download Report</span>
                </button>
              </div>
              
              <div className="bg-gray-50 rounded-lg p-6 font-mono text-sm">
                <pre className="whitespace-pre-wrap text-gray-800">
                  {generateReport()}
                </pre>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AnalysisResults;